---
- name: update conf file to turn maintenance mode off
  blockinfile:
    path: "{{ maintenance_nginx_conf }}"
    insertafter: "SYSTEM_MAINTENANCE_PLACEHOLDER"
    state: absent
  notify: restart nginx

- name: remove maintenance page
  file:
    path: "{{ maintenance_html_dir }}/{{ maintenance_page }}"
    state: absent
  notify: restart nginx

- name: start services back up (in reverse order than they were stopped)
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ maintenance_services_to_pause | reverse | list }}"
