---
- name: update conf file to turn maintenance mode off
  lineinfile:
    path: "{{ maintenance_nginx_conf }}"
    line: "return 503;"
    state: absent
    mode: 0644
  notify: restart nginx

- name: start monit
  systemd:
    name: monit
    enabled: yes
    state: started
