---
- name: temporarily stop monitoring services
  systemd:
    name: monit
    enabled: yes
    state: stopped

- name: set rounding based on estimated time
  set_fact:
    rounding_min: |
      {% if maintenance_min|int <= 15 %}5
      {% elif maintenance_min|int <= 60 %}15
      {% elif maintenance_min|int <= 180 %}30
      {% else %}60{% endif %}

- name: get rounded estimated end time of maintenance
  shell: |
    est_time=`date -d'+{{ maintenance_rounding_min|int + maintenance_min|int }} minutes' '+%s'`
    rounded=$(($est_time - ($est_time % {{ rounding_min|int * 60 }}) ))
    TZ={{ maintenance_time_zone }} date -d"@$rounded" '+%b %d at %l:%M%P %Z'
  register: maintenance_end_time
  changed_when: false

- name: generate maintenance page
  template:
    src: "{{ maintenance_custom_page if maintenance_custom_page is defined else 'system_maintenance.html.j2' }}"
    dest: "{{ maintenance_html_dir }}/{{ maintenance_page }}"
  notify: restart nginx

- name: update conf file to turn maintenance mode on
  lineinfile:
    path: "{{ maintenance_nginx_conf }}"
    line: "return 503;"
    insertafter: system_maintenance.conf
    state: present
    mode: 0644
  notify: restart nginx
