---
- name: copy shared config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/global/{{ item | basename }}"
  with_items:
    - system_maintenance.conf
    - "{{ maintenance_page }}"
  notify: restart nginx
